# Generated by Django 3.0.5 on 2020-05-04 23:03

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=150, verbose_name='Proje Başlığı')),
                ('detail', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Fotoğraf')),
                ('rate', models.IntegerField(blank=True, default=0, verbose_name='Değerlendirme')),
                ('status', models.CharField(blank=True, choices=[('Yayında', 'Yayında'), ('Yeni', 'Yeni'), ('Kaldırıldı', 'Kaldırıldı')], default='Yeni', max_length=15)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('slug', models.SlugField(blank=True, default='')),
            ],
        ),
    ]
