# Generated by Django 3.0.5 on 2020-05-04 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200505_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.CharField(blank=True, max_length=250, verbose_name='Proje Linki'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(blank=True, max_length=250, verbose_name='Proje Başlığı'),
        ),
    ]
