# Generated by Django 3.0.5 on 2020-05-04 14:12

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='Site Adı')),
                ('keywords', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('company', models.CharField(blank=True, max_length=100, verbose_name='Şirket Adı')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Adres')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Telefon')),
                ('fax', models.CharField(blank=True, max_length=15, verbose_name='Fax')),
                ('email', models.CharField(blank=True, max_length=100, verbose_name='Email')),
                ('smtpserver', models.CharField(blank=True, max_length=100)),
                ('smtpemail', models.CharField(blank=True, max_length=100)),
                ('smtppassword', models.CharField(blank=True, max_length=100)),
                ('smtpport', models.CharField(blank=True, max_length=10)),
                ('icon', models.ImageField(blank=True, upload_to='', verbose_name='Logo')),
                ('facebook', models.CharField(blank=True, max_length=100)),
                ('twitter', models.CharField(blank=True, max_length=100)),
                ('instagram', models.CharField(blank=True, max_length=100)),
                ('aboutme', ckeditor.fields.RichTextField()),
                ('contact', ckeditor.fields.RichTextField()),
                ('status', models.CharField(choices=[('TRUE', 'EVET'), ('FALSE', 'HAYIR')], max_length=10)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
