# Generated by Django 3.0.5 on 2020-05-04 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFormMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('surname', models.CharField(blank=True, max_length=50)),
                ('email', models.CharField(blank=True, max_length=150)),
                ('subject', models.CharField(blank=True, max_length=150)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('ip', models.CharField(blank=True, max_length=150)),
                ('note', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('Yeni', 'Yeni'), ('Okundu', 'Okundu'), ('Cevaplandı', 'Cevaplandı')], default='Yeni', max_length=10)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
