# Generated by Django 3.0.5 on 2020-05-04 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_contactformmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformmessage',
            name='email',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='contactformmessage',
            name='ip',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='contactformmessage',
            name='message',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contactformmessage',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contactformmessage',
            name='subject',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='contactformmessage',
            name='surname',
            field=models.CharField(max_length=50),
        ),
    ]
