# Generated by Django 3.0.5 on 2020-05-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20200505_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='github',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='setting',
            name='kariyer',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
