# Generated by Django 3.0.5 on 2020-05-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20200505_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='career',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
