# Generated by Django 3.0.5 on 2020-05-05 12:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_setting_career'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='career',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
