# Generated by Django 3.0.5 on 2020-05-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20200505_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='youtube',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
