# Generated by Django 3.0.5 on 2020-05-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_setting_youtube'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='welcoming',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
