# Generated by Django 3.0.5 on 2020-05-05 14:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_setting_welcoming'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='welcoming',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
