# Generated by Django 3.0.5 on 2020-05-03 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20200503_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.TextField(blank=True, max_length=100, verbose_name='Başlık'),
        ),
    ]
