# Generated by Django 3.0.5 on 2020-05-03 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_auto_20200503_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='status',
        ),
    ]
