# Generated by Django 3.0.5 on 2020-05-03 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_remove_blog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='status',
            field=models.CharField(blank=True, choices=[('Yayında', 'Yayında'), ('Yeni', 'Yeni'), ('Kaldırıldı', 'Kaldırıldı')], default='Yeni', max_length=15),
        ),
    ]
