# Generated by Django 3.0.5 on 2020-05-03 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_blog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='rate',
            field=models.IntegerField(blank=True, default=0, verbose_name='Değerlendirme'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='readings',
            field=models.IntegerField(blank=True, default=0, verbose_name='Okunma Sayısı'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
