# Generated by Django 3.0.5 on 2020-05-04 10:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_auto_20200503_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='description',
            field=models.TextField(blank=True, default=' ', verbose_name='Blog Özet'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Blog İçeriği'),
        ),
    ]
